// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureChatUserMicroService.Infrastructure;

#nullable disable

namespace SecureChatUserMicroService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    partial class UserServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UserMicroService")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureChatUserMicroService.Domain.Entities.BlockUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate")
                        .HasComment("Дата окончания");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasComment("Активна ли блокировка");

                    b.Property<Instant>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate")
                        .HasComment("Дата начала");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("BlockUsers", "UserMicroService");
                });

            modelBuilder.Entity("SecureChatUserMicroService.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedTime")
                        .HasComment("Дата создания");

                    b.Property<Instant?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeleteTime")
                        .HasComment("Дата удаления");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Email")
                        .HasComment("Почта");

                    b.Property<Instant>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastUpdateTime")
                        .HasComment("Дата обновления");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "UserMicroService");
                });

            modelBuilder.Entity("SecureChatUserMicroService.Domain.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AvatarUrl")
                        .HasComment("Ссылка на аватар");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsBlocked")
                        .HasComment("Признак блокировки");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Name")
                        .HasComment("Имя");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nickname")
                        .HasComment("Ник");

                    b.Property<Guid>("Status")
                        .HasColumnType("uuid")
                        .HasColumnName("Status")
                        .HasComment("Статус");

                    b.Property<string>("StatusQuote")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("StatusQuote")
                        .HasComment("Цитата(статус)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles", "UserMicroService");
                });

            modelBuilder.Entity("SecureChatUserMicroService.Domain.Entities.BlockUserEntity", b =>
                {
                    b.HasOne("SecureChatUserMicroService.Domain.Entities.UserProfileEntity", "UserProfile")
                        .WithMany("BlockUsers")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SecureChatUserMicroService.Domain.Entities.UserProfileEntity", b =>
                {
                    b.HasOne("SecureChatUserMicroService.Domain.Entities.UserEntity", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureChatUserMicroService.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("SecureChatUserMicroService.Domain.Entities.UserProfileEntity", b =>
                {
                    b.Navigation("BlockUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
